name    'puppet-solrcloud'
version '0.0.1'
source  'https://github.com/DiceHoldingsInc/puppet-solrcloud.git'
license 'MIT'
summary 'A puppet module for solrcloud'
description 'Configure and set up a multi-core solr instance'
project_page 'https://github.com/DiceHoldingsInc/puppet-solrcloud'
